services:
  server:
    build: 
      context: server
    # image: fujimitsu000/ttt-server
    ports:
      - 8000:8000
    tty: true
    env_file:
      - .env
    links:
      - postgres
    container_name: ttt-server
    depends_on:
      - postgres
    networks:
      - public
      - private

  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - private
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: client
    # image: fujimitsu000/ttt-client
    ports:
      - 3000:3000
    container_name: ttt-client
    networks:
      - public
    depends_on:
      - server
networks:
  public:
  private:
volumes:
  back-notused:
  postgres-data:

